### ISSUE TITLE
How to run a dev version of this repo?

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-visual-verifier#18]
I followed the instructions -- running just `./manage build` and then `./manage start` and got an error `The CONTROLLER_URL has not been set.`. Is there something missing in the instructions?  For example, is an instance of vc-authn-oidc supposed to be running already?

**Comment by cr-tech-repo** [comment]
i think the documentation is missing, i had to run the vc-authn-oidc to get past this issue. However, ran into an other issue with ./manage start i.e. ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/opt/app-root/lib64/python3.9/site-packages/django/utils/translation/__init__.py)

**Comment by WadeBarnes** [comment]
It does require an instance of `vc-authn-oidc` to be running.  However the changes made in `vc-authn-oidc` [here](https://github.com/bcgov/vc-authn-oidc/issues/145) could affect the wring [here](https://github.com/bcgov/vc-visual-verifier/blob/main/docker/manage#L225).
As for the `CONTROLLER_URL`, that should be set automatically here; https://github.com/bcgov/vc-visual-verifier/blob/main/docker/manage#L328-L336

**Comment by WadeBarnes** [comment]
@esune ^

**Comment by esune** [comment]
While teh code is not the same, this repo works teh same way as the `oidc-django` demo in the `vc-authn-oidc` repo: https://github.com/bcgov/vc-authn-oidc/tree/main/demo

There currently is no way of running this repo by itself, as @WadeBarnes pointed out it will require a (configured) instance ov vc-authn. The code in this repo is just a client webapp that can use vc-authn as OIDC authentication method.
