### ISSUE TITLE
[Question] - Is it possible to add some more details about this service in the readme file?

### ISSUE THREAD

**Issue by dinbtechit** [bcgov/vc-visual-verifier#23]
I am trying to evaluate if we need this service for NS Gov. (On a side note - We are building an issuer kit for Nova Scotia with a slightly different architecture so trying to understand if we can leverage this service.)

I was wondering if it is possible to add the following details to the readme file. 

1.  Overview of this service in the broader context. (If possible some architecture diagram) 😀
2.  API docs for utilizing this service.

The reason for the question is, I am curious if this service is actually used for video verification as shown in the youtube video

[![image](https://user-images.githubusercontent.com/17984781/198153397-5d9d2391-c836-444a-8c16-00640679e8fe.png)](https://www.youtube.com/watch?v=nWC7H3LGlrE&t=65s)

Thank you!

**Comment by WadeBarnes** [comment]
The visual verifier does not provide video verification as depicted in the video above, I provides a very simplified view of a persons presented credentials for visual verification and approval (screenshot below).  It is part of the Safe Entry BC Demo.  You can see it in action by walking through the demo; https://digital.gov.bc.ca/digital-trust/projects-and-initiatives/safe-entry-bc-demo/

A list of components that go into the Safe Entry BC Demo can be found here; https://github.com/bcgov/essential-services-delivery

![image](https://user-images.githubusercontent.com/10504350/198279983-c062fb36-ccbc-46cc-84f9-ca785d5be7ed.png)

![image](https://user-images.githubusercontent.com/10504350/198280621-6919083f-97f1-4f71-a94b-a2aedc2a1dad.png)

**Comment by dinbtechit** [comment]
Ahh that makes sense! Thank you so much for the thorough explanation. 🙏
